### ISSUE TITLE
Manually Downloading and Placing the file does not work. still it downloads automatically from huggingface

### ISSUE THREAD

**Issue by axiomgraph** [1038lab/ComfyUI-RMBG#1]
![Screenshot 2024-11-18 052559](https://github.com/user-attachments/assets/2282f84b-8d8b-4874-842c-acc67cba732e)

**Comment by 1038lab** [comment]
hank you for pointing that out. You're correct—the manual download method isn't working as expected. I appreciate you bringing this up, and I’ll make sure to review the README for further clarification. Let me know if there's anything else I can assist with!
