### ISSUE TITLE
Model load failed (download ok, but load failed)

### ISSUE THREAD

**Issue by coollofty** [1038lab/ComfyUI-RMBG#3]
```
File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-RMBG\ailab_RMBG.py", line 87, in remove_background
    raise RuntimeError(f"Error loading RMBG model: {str(e)}")
RuntimeError: Error loading RMBG model: Expecting value: line 1 column 1 (char 0)
```

any suggestions?

**Comment by 1038lab** [comment]
looks like its model download issue, try delete the RMBG-2.0 floder located at /comfyui/models/RMBG/

**Comment by coollofty** [comment]
The auto download address is: https://huggingface.co/briaai/RMBG-2.0/resolve/main/adapter_config.json but it is not exists, I got an Entry not found when I accessed this address from the browser，so I downloaded it manually, which is git clone from https://huggingface.co/briaai/RMBG-2.0/tree/main, but the error that occurred is as described above. I am certain that downloading the correct file is not a problem, and this has been verified

**Comment by 1038lab** [comment]
Update custom node will fix your issues
